//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirlineReservationEntities : DbContext
    {
        public AirlineReservationEntities()
            : base("name=AirlineReservationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblClass> tblClasses { get; set; }
        public virtual DbSet<tblFare> tblFares { get; set; }
        public virtual DbSet<tblFlight> tblFlights { get; set; }
        public virtual DbSet<tblFlightBook> tblFlightBooks { get; set; }
        public virtual DbSet<tblFlightBookDetail> tblFlightBookDetails { get; set; }
        public virtual DbSet<tblFlightSchedule> tblFlightSchedules { get; set; }
        public virtual DbSet<tblFlightSeat> tblFlightSeats { get; set; }
        public virtual DbSet<tblFrequentFlightSchedule> tblFrequentFlightSchedules { get; set; }
        public virtual DbSet<tblPassengerDetail> tblPassengerDetails { get; set; }
        public virtual DbSet<tblPassengerType> tblPassengerTypes { get; set; }
        public virtual DbSet<tblRoute> tblRoutes { get; set; }
        public virtual DbSet<tblTripType> tblTripTypes { get; set; }
        public virtual DbSet<tblUserInformation> tblUserInformations { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
    }
}
