//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlightSeat
    {
        public int ID { get; set; }
        public int FlightID { get; set; }
        public int ClassID { get; set; }
        public int NoOfSeat { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblFlight tblFlight { get; set; }
    }
}
